return {
  read = require("sia.tools.read"),
  grep = require("sia.tools.grep"),
  glob = require("sia.tools.glob"),
  edit = require("sia.tools.edit"),
  write = require("sia.tools.write"),
  rename = require("sia.tools.rename"),
  remove = require("sia.tools.remove"),
  bash = require("sia.tools.bash"),
  locations = require("sia.tools.locations"),
  workspace = require("sia.tools.workspace"),
  agent = require("sia.tools.agent"),
  plan = require("sia.tools.plan"),
  diagnostics = require("sia.tools.diagnostics"),
  compact = require("sia.tools.compact"),
  fetch = require("sia.tools.fetch"),
  websearch = require("sia.tools.websearch"),
}
