return {
  read = require("sia.tools.read"),
  grep = require("sia.tools.grep"),
  glob = require("sia.tools.glob"),
  edit = require("sia.tools.edit"),
  insert = require("sia.tools.insert"),
  write = require("sia.tools.write"),
  rename = require("sia.tools.rename"),
  remove = require("sia.tools.remove"),
  bash = require("sia.tools.bash"),
  locations = require("sia.tools.locations"),
  workspace = require("sia.tools.workspace"),
  task = require("sia.tools.agent"),
  plan = require("sia.tools.plan"),
  diagnostics = require("sia.tools.diagnostics"),
  fetch = require("sia.tools.fetch"),
  websearch = require("sia.tools.websearch"),
  read_todos = require("sia.tools.read_todos"),
  write_todos = require("sia.tools.write_todos"),
  history = require("sia.tools.history"),
  memory = require("sia.tools.memory"),
  lsp = require("sia.tools.lsp"),
}
