return {
  agent = require("sia.tools.agent"),
  read = require("sia.tools.read"),
  grep = require("sia.tools.grep"),
  glob = require("sia.tools.glob"),
  edit = require("sia.tools.edit"),
  insert = require("sia.tools.insert"),
  write = require("sia.tools.write"),
  bash = require("sia.tools.bash"),
  task = require("sia.tools.agent"),
  diagnostics = require("sia.tools.diagnostics"),
  fetch = require("sia.tools.fetch"),
  websearch = require("sia.tools.websearch"),
  read_todos = require("sia.tools.read_todos"),
  write_todos = require("sia.tools.write_todos"),
  memory = require("sia.tools.memory"),
  ask_user = require("sia.tools.ask_user"),
  apply_diff = require("sia.tools.apply_diff"),
}
